"""add cart

Revision ID: 23d6ef8a8b14
Revises: 82c56e165714
Create Date: 2023-01-26 14:13:03.877196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d6ef8a8b14'
down_revision = '82c56e165714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cart', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cart')
    # ### end Alembic commands ###
