"""add nick

Revision ID: 2820b78a2d6a
Revises: 1d4839f7c144
Create Date: 2023-01-10 19:28:39.467493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2820b78a2d6a'
down_revision = '1d4839f7c144'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nick', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nick')
    # ### end Alembic commands ###
