"""add jump

Revision ID: 469acead12c4
Revises: 23d6ef8a8b14
Create Date: 2023-01-28 09:35:09.746536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469acead12c4'
down_revision = '23d6ef8a8b14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jumps',
    sa.Column('jid', sa.String(length=6), nullable=False),
    sa.Column('target', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('qrcode', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('jid')
    )
    op.create_index(op.f('ix_jumps_jid'), 'jumps', ['jid'], unique=False)
    op.create_index(op.f('ix_jumps_target'), 'jumps', ['target'], unique=False)
    op.create_index(op.f('ix_jumps_type'), 'jumps', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jumps_type'), table_name='jumps')
    op.drop_index(op.f('ix_jumps_target'), table_name='jumps')
    op.drop_index(op.f('ix_jumps_jid'), table_name='jumps')
    op.drop_table('jumps')
    # ### end Alembic commands ###
