"""del cart

Revision ID: 4a9ffba020cc
Revises: 8cf0c5966225
Create Date: 2023-09-02 09:51:27.112733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a9ffba020cc'
down_revision = '8cf0c5966225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cart', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
