"""add ocr for file

Revision ID: 72075a10aeab
Revises: 2820b78a2d6a
Create Date: 2023-01-12 09:17:31.473807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72075a10aeab'
down_revision = '2820b78a2d6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('ocr', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'ocr')
    # ### end Alembic commands ###
