"""add md5

Revision ID: 82c56e165714
Revises: abf5ef723e98
Create Date: 2023-01-22 10:18:07.676292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c56e165714'
down_revision = 'abf5ef723e98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('md5', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_files_md5'), 'files', ['md5'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_md5'), table_name='files')
    op.drop_column('files', 'md5')
    # ### end Alembic commands ###
