"""delete status

Revision ID: 8cf0c5966225
Revises: f655ff5b8850
Create Date: 2023-08-08 10:29:21.234484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf0c5966225'
down_revision = 'f655ff5b8850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('status', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
