"""add task

Revision ID: abf5ef723e98
Revises: cf998c260ac9
Create Date: 2023-01-20 23:00:31.012622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf5ef723e98'
down_revision = 'cf998c260ac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('tid', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('status', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_index(op.f('ix_tasks_created'), 'tasks', ['created'], unique=False)
    op.create_index(op.f('ix_tasks_tid'), 'tasks', ['tid'], unique=False)
    op.create_index(op.f('ix_tasks_type'), 'tasks', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_tid'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
