"""update status

Revision ID: cf998c260ac9
Revises: fa1d4d4e73be
Create Date: 2023-01-18 22:10:17.394639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf998c260ac9'
down_revision = 'fa1d4d4e73be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('papers', 'receipt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('receipt', sa.BOOLEAN(), nullable=True))
    op.drop_column('papers', 'status')
    # ### end Alembic commands ###
