"""add assign

Revision ID: f655ff5b8850
Revises: 469acead12c4
Create Date: 2023-01-29 18:09:31.072676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f655ff5b8850'
down_revision = '469acead12c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigns',
    sa.Column('aid', sa.String(length=36), nullable=False),
    sa.Column('egid', sa.String(length=36), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('ext', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['egid'], ['examgroups.egid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_assigns_aid'), 'assigns', ['aid'], unique=False)
    op.create_index(op.f('ix_assigns_md5'), 'assigns', ['md5'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assigns_md5'), table_name='assigns')
    op.drop_index(op.f('ix_assigns_aid'), table_name='assigns')
    op.drop_table('assigns')
    # ### end Alembic commands ###
