"""optimize uuid store

Revision ID: fa1d4d4e73be
Revises: 72075a10aeab
Create Date: 2023-01-14 18:06:38.192885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1d4d4e73be'
down_revision = '72075a10aeab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
